apiVersion: v1
kind: Service
metadata:
  name: reviews
  annotations:
    mcm.ibm.com/service-discovery: "{}"
  labels:
    app.kubernetes.io/name: reviews
    app.kubernetes.io/instance: bookinfo-demo
    appname: bookinfo-demo
    purpose: icam-demo
spec:
  ports:
    - port: 9080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: reviews
    app.kubernetes.io/instance: bookinfo-demo

